// e95/frontend/src/components/ControlPanel.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import type { MeasureResult } from '@/types/quantum';

const props = defineProps<{
  numQubits: number;
  isRunning: boolean;
  lastMeasureResult: MeasureResult | null;
}>();

const emit = defineEmits<{
  (e: 'update:numQubits', value: number): void;
  (e: 'run'): void;
  (e: 'reset'): void;
  (e: 'measure', qubit: number): void;
}>();

const selectedQubit = ref(0);
const qubitOptions = computed(() => Array.from({ length: props.numQubits }, (_, i) => i));

function handleNumQubitsChange(event: Event) {
  const target = event.target as HTMLInputElement;
  emit('update:numQubits', parseInt(target.value));
}

function handleMeasure() {
  emit('measure', selectedQubit.value);
}
</script>

<template>
  <div class="bg-slate-800/50 rounded-xl p-4 backdrop-blur-sm border border-slate-700">
    <h3 class="text-lg font-semibold text-cyan-400 mb-4 flex items-center gap-2">
      <span class="text-2xl">🎛️</span>
      控制面板
    </h3>

    <div class="space-y-4">
      <div>
        <label class="block text-sm text-slate-300 mb-2">
          量子比特数量: <span class="text-cyan-400 font-mono">{{ numQubits }}</span>
        </label>
        <input
          type="range"
          :value="numQubits"
          @input="handleNumQubitsChange"
          min="1"
          max="12"
          step="1"
          class="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-cyan-400"
        />
        <div class="flex justify-between text-xs text-slate-500 mt-1">
          <span>1</span>
          <span>6</span>
          <span>12</span>
        </div>
      </div>

      <div class="grid grid-cols-2 gap-3">
        <button
          @click="emit('run')"
          :disabled="isRunning"
          class="px-4 py-3 bg-gradient-to-r from-cyan-500 to-blue-500 text-white font-semibold rounded-lg hover:from-cyan-400 hover:to-blue-400 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-cyan-500/20"
        >
          {{ isRunning ? '运行中...' : '▶ 运行电路' }}
        </button>
        <button
          @click="emit('reset')"
          class="px-4 py-3 bg-slate-700 text-slate-200 font-semibold rounded-lg hover:bg-slate-600 transition-all"
        >
          ↺ 重置
        </button>
      </div>

      <div class="border-t border-slate-700 pt-4">
        <h4 class="text-sm font-medium text-slate-300 mb-3">量子测量</h4>
        <div class="flex gap-2">
          <select
            v-model="selectedQubit"
            class="flex-1 px-3 py-2 bg-slate-700 text-white rounded-lg border border-slate-600 focus:border-cyan-400 focus:outline-none"
          >
            <option v-for="q in qubitOptions" :key="q" :value="q">
              q{{ q }}
            </option>
          </select>
          <button
            @click="handleMeasure"
            :disabled="isRunning"
            class="px-4 py-2 bg-purple-500 text-white font-medium rounded-lg hover:bg-purple-400 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            测量
          </button>
        </div>
      </div>

      <div
        v-if="lastMeasureResult"
        class="bg-purple-500/10 border border-purple-500/30 rounded-lg p-3"
      >
        <div class="text-sm text-purple-300 mb-1">最近测量结果</div>
        <div class="flex items-center gap-3">
          <div class="text-2xl font-mono font-bold text-purple-400">
            |{{ lastMeasureResult.result }}⟩
          </div>
          <div class="text-xs text-slate-400">
            量子比特 q{{ lastMeasureResult.qubit }}
          </div>
        </div>
      </div>

      <div class="bg-slate-900/50 rounded-lg p-3 border border-slate-700">
        <h4 class="text-sm font-medium text-slate-300 mb-2">快捷示例</h4>
        <div class="text-xs text-slate-400 space-y-1">
          <p>• <span class="text-cyan-400">H</span> 创建叠加态</p>
          <p>• <span class="text-cyan-400">H + CNOT</span> 创建 Bell 纠缠态</p>
          <p>• <span class="text-cyan-400">X</span> 翻转量子比特</p>
          <p>• <span class="text-cyan-400">S/T</span> 添加相位</p>
        </div>
      </div>
    </div>
  </div>
</template>

// e29/src/components/ControlPanel.tsx
import { SearchState, AlgorithmType } from '../types';

interface ControlPanelProps {
  isRunning: boolean;
  searchState: SearchState;
  speed: number;
  algorithm: AlgorithmType;
  startNode: string;
  targetNode: string;
  nodeOptions: string[];
  onSpeedChange: (speed: number) => void;
  onAlgorithmChange: (algorithm: AlgorithmType) => void;
  onStartNodeChange: (node: string) => void;
  onTargetNodeChange: (node: string) => void;
  onStart: () => void;
  onReset: () => void;
  totalNodes: number;
}

export const ControlPanel = ({
  isRunning,
  searchState,
  speed,
  algorithm,
  startNode,
  targetNode,
  nodeOptions,
  onSpeedChange,
  onAlgorithmChange,
  onStartNodeChange,
  onTargetNodeChange,
  onStart,
  onReset,
  totalNodes,
}: ControlPanelProps) => {
  return (
    <div className="controls-bg rounded-2xl p-6 space-y-5 max-h-screen overflow-y-auto">
      <div>
        <h1 className="text-2xl font-bold text-white mb-2">
          图搜索算法可视化
        </h1>
        <p className="text-slate-400 text-sm">
          BFS / A* 算法执行过程可视化
        </p>
      </div>

      <div className="space-y-2">
        <label className="text-slate-300 text-sm font-medium">算法选择</label>
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => onAlgorithmChange('BFS')}
            disabled={isRunning}
            className={`py-2 px-3 rounded-lg text-sm font-semibold transition-all ${
              algorithm === 'BFS'
                ? 'bg-blue-500 text-white shadow-lg shadow-blue-500/30'
                : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
            }`}
          >
            BFS
          </button>
          <button
            onClick={() => onAlgorithmChange('ASTAR')}
            disabled={isRunning}
            className={`py-2 px-3 rounded-lg text-sm font-semibold transition-all ${
              algorithm === 'ASTAR'
                ? 'bg-violet-500 text-white shadow-lg shadow-violet-500/30'
                : 'bg-slate-700 text-slate-300 hover:bg-slate-600'
            }`}
          >
            A*
          </button>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3">
        <div className="space-y-2">
          <label className="text-slate-300 text-sm font-medium">起点</label>
          <select
            value={startNode}
            onChange={(e) => onStartNodeChange(e.target.value)}
            disabled={isRunning}
            className="w-full bg-slate-700 text-white py-2 px-3 rounded-lg text-sm border border-slate-600 focus:border-blue-500 focus:outline-none"
          >
            {nodeOptions.map((node) => (
              <option key={node} value={node}>{node}</option>
            ))}
          </select>
        </div>
        <div className="space-y-2">
          <label className="text-slate-300 text-sm font-medium">终点</label>
          <select
            value={targetNode}
            onChange={(e) => onTargetNodeChange(e.target.value)}
            disabled={isRunning}
            className="w-full bg-slate-700 text-white py-2 px-3 rounded-lg text-sm border border-slate-600 focus:border-blue-500 focus:outline-none"
          >
            {nodeOptions.map((node) => (
              <option key={node} value={node}>{node}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-slate-300 text-sm">动画速度</span>
          <span className="text-blue-400 font-semibold text-sm">{speed}ms</span>
        </div>
        <input
          type="range"
          min="100"
          max="2000"
          step="100"
          value={speed}
          onChange={(e) => onSpeedChange(Number(e.target.value))}
          disabled={isRunning}
          className="slider w-full"
        />
      </div>

      <div className="flex gap-3">
        <button
          onClick={onStart}
          disabled={isRunning || searchState.isComplete || startNode === targetNode}
          className="btn-primary flex-1 py-3 px-4 rounded-xl text-white font-semibold text-sm"
        >
          {searchState.isComplete 
            ? searchState.foundTarget 
              ? '已找到路径' 
              : '未找到'
            : isRunning 
              ? '执行中...' 
              : `开始 ${algorithm === 'ASTAR' ? 'A*' : 'BFS'}`
          }
        </button>
        <button
          onClick={onReset}
          className="btn-secondary py-3 px-6 rounded-xl text-white font-semibold text-sm"
        >
          重置
        </button>
      </div>

      <div className="status-card rounded-xl p-4 space-y-4">
        <h3 className="text-white font-semibold text-sm border-b border-slate-700 pb-2">
          算法状态
        </h3>
        
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-slate-800/50 rounded-lg p-3">
            <div className="text-slate-400 text-xs mb-1">当前步骤</div>
            <div className="text-2xl font-bold text-blue-400">{searchState.step}</div>
          </div>
          <div className="bg-slate-800/50 rounded-lg p-3">
            <div className="text-slate-400 text-xs mb-1">已访问节点</div>
            <div className="text-2xl font-bold text-emerald-400">
              {searchState.visited.length} / {totalNodes}
            </div>
          </div>
        </div>

        {searchState.current && (
          <div className="bg-amber-500/10 border border-amber-500/30 rounded-lg p-3">
            <div className="text-amber-400 text-xs mb-1">当前访问节点</div>
            <div className="text-3xl font-bold text-amber-400 flex items-center gap-2">
              <span className="w-3 h-3 bg-amber-400 rounded-full animate-pulse"></span>
              {searchState.current}
            </div>
          </div>
        )}

        {searchState.isComplete && searchState.foundTarget && (
          <div className="bg-emerald-500/10 border border-emerald-500/30 rounded-lg p-3">
            <div className="text-emerald-400 text-sm font-semibold flex items-center gap-2 mb-2">
              <span>✓</span>
              {algorithm === 'ASTAR' ? 'A*' : 'BFS'} 搜索完成！
            </div>
            <div className="text-slate-400 text-xs mb-2">最短路径：</div>
            <div className="flex flex-wrap gap-1">
              {searchState.path.map((node, idx) => (
                <span key={node} className="inline-flex items-center">
                  <span className="bg-emerald-600 text-white px-2 py-0.5 rounded text-xs font-mono">
                    {node}
                  </span>
                  {idx < searchState.path.length - 1 && (
                    <span className="text-emerald-400 mx-0.5">→</span>
                  )}
                </span>
              ))}
            </div>
            <div className="text-slate-400 text-xs mt-2">
              路径长度：{searchState.path.length} 步
            </div>
          </div>
        )}

        {searchState.isComplete && !searchState.foundTarget && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3">
            <div className="text-red-400 text-sm font-semibold flex items-center gap-2">
              <span>✗</span>
              未找到路径：节点不可达
            </div>
          </div>
        )}

        {searchState.queue.length > 0 && !searchState.isComplete && (
          <div className="bg-slate-800/50 rounded-lg p-3">
            <div className="text-slate-400 text-xs mb-2">
              {algorithm === 'ASTAR' ? '开放集' : '待访问队列'}
            </div>
            <div className="flex flex-wrap gap-2 max-h-20 overflow-y-auto">
              {searchState.queue.slice(0, 8).map((node) => (
                <span
                  key={node}
                  className="bg-slate-700 text-slate-300 px-2 py-1 rounded text-xs font-mono"
                >
                  {node}
                </span>
              ))}
              {searchState.queue.length > 8 && (
                <span className="text-slate-500 text-xs py-1">
                  +{searchState.queue.length - 8} 更多
                </span>
              )}
            </div>
          </div>
        )}
      </div>

      <div className="space-y-2">
        <h3 className="text-white font-semibold text-sm">图例</h3>
        <div className="grid grid-cols-1 gap-2">
          <div className="flex items-center gap-3">
            <div className="w-4 h-4 rounded-full bg-slate-500"></div>
            <span className="text-slate-400 text-sm">未访问</span>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-4 h-4 rounded-full bg-emerald-500"></div>
            <span className="text-slate-400 text-sm">已访问</span>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-4 h-4 rounded-full bg-amber-500 animate-pulse"></div>
            <span className="text-slate-400 text-sm">当前节点</span>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-4 h-4 rounded-full bg-pink-500"></div>
            <span className="text-slate-400 text-sm">路径节点</span>
          </div>
          <div className="flex items-center gap-3">
            <div className="w-8 h-1 rounded bg-pink-500"></div>
            <span className="text-slate-400 text-sm">最短路径</span>
          </div>
        </div>
      </div>

      <div className="border-t border-slate-700 pt-4">
        <p className="text-slate-500 text-xs">
          提示：拖拽节点可调整位置，滚轮可缩放画布
        </p>
      </div>
    </div>
  );
};
